export const SUPPORTED_LANGUAGES = [
  { name: "English", code: "english" },
  { name: "Spanish", code: "spanish" },
  { name: "French", code: "french" },
  { name: "German", code: "german" },
  { name: "Italian", code: "italian" },
  { name: "Portuguese", code: "portuguese" },
  { name: "Mandarin", code: "chinese" },
  { name: "Japanese", code: "japanese" },
  { name: "Korean", code: "korean" },
  { name: "Arabic", code: "arabic" },
  { name: "Russian", code: "russian" },
  { name: "Swedish", code: "swedish" },
  { name: "Thai", code: "thai" },
  { name: "Turkish", code: "turkish" },
  { name: "Ukrainian", code: "ukrainian" },
  { name: "Urdu", code: "urdu" },
  { name: "Hindi", code: "hindi" },
  { name: "Dutch", code: "dutch" },
  { name: "Polish", code: "polish" },
  { name: "Brazilian", code: "brazilian" },
  { name: "Hebrew", code: "hebrew" },
] as const;

export const BROWSER_TO_APP_LANG_CODES: Record<string, string> = {
  en: "english",
  es: "spanish",
  fr: "french",
  de: "german",
  it: "italian",
  pt: "portuguese",
  zh: "chinese",
  ja: "japanese",
  ko: "korean",
  ar: "arabic",
  ru: "russian",
  sv: "swedish",
  th: "thai",
  tr: "turkish",
  uk: "ukrainian",
  ur: "urdu",
  hi: "hindi",
  nl: "dutch",
  pl: "polish",
  "pt-BR": "brazilian",
  he: "hebrew",
};
